// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV4WUfhyAKEnP3b_gKbHk6R19Ql1xZp-Y',
    appId: '1:230836006855:web:0b803d318593773b5273e2',
    messagingSenderId: '230836006855',
    projectId: 'go-feast',
    authDomain: 'go-feast.firebaseapp.com',
    storageBucket: 'go-feast.firebasestorage.app',
    measurementId: 'G-HYXJZJ9FSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBINr62-w3BWLpVwK-qtu8XFfi9ExvgWYM',
    appId: '1:230836006855:android:5dc9c3da3058f0945273e2',
    messagingSenderId: '230836006855',
    projectId: 'go-feast',
    storageBucket: 'go-feast.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABVx-kj1emNLHzTvfmGiObb-9n_FJkRdU',
    appId: '1:230836006855:ios:7ca4b8a3bc8a654c5273e2',
    messagingSenderId: '230836006855',
    projectId: 'go-feast',
    storageBucket: 'go-feast.firebasestorage.app',
    iosBundleId: 'com.example.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABVx-kj1emNLHzTvfmGiObb-9n_FJkRdU',
    appId: '1:230836006855:ios:7ca4b8a3bc8a654c5273e2',
    messagingSenderId: '230836006855',
    projectId: 'go-feast',
    storageBucket: 'go-feast.firebasestorage.app',
    iosBundleId: 'com.example.driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV4WUfhyAKEnP3b_gKbHk6R19Ql1xZp-Y',
    appId: '1:230836006855:web:6dda495b99fb62285273e2',
    messagingSenderId: '230836006855',
    projectId: 'go-feast',
    authDomain: 'go-feast.firebaseapp.com',
    storageBucket: 'go-feast.firebasestorage.app',
    measurementId: 'G-SMRVTJE1B1',
  );
}
