const Map<String, String> _storeCategoryLabels = {
  "banh_truyen_thong": "Bánh truyền thống",
  "lau_nuong": "Lẩu & Nướng",
  "do_an_dinh_duong": "Đồ ăn dinh dưỡng",
  "do_uong_khong_con": "Đồ uống không cồn",
  "com": "Cơm",
  "tra_sua": "Trà sữa",
  "do_an_vat": "Đồ ăn vặt",
  "ga": "Gà",
  "ca_phe": "Cà phê",
  "trang_mieng": "Tráng miệng",
  "bun": "Bún",
  "tra": "Trà",
  "banh_au_a": "Bánh Âu Á",
  "bun_pho_my": "Bún/Phở/Mỳ",
  "nuoc_ep_sinh_to": "Nước ép & Sinh tố",
  "banh_trang": "Bánh tráng",
  "chao_sup": "Cháo/Súp",
  "do_an_nhanh": "Đồ ăn nhanh",
  "hai_san": "Hải sản",
  "banh_mi": "Bánh mì",
  "pasta": "Pasta",
  "heo": "Heo",
  "lau": "Lẩu",
  "ga_ran": "Gà rán",
  "bo": "Bò",
  "am_thuc_quoc_te": "Ẩm thực quốc tế",
  "cac_mon_cuon": "Các món cuốn",
  "ca": "Cá",
  "do_chay": "Đồ chay",
  "chuc_mung": "Chúc mừng",
};

String categoryLabel(String raw) => _storeCategoryLabels[raw] ?? raw;
